import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import apiService from '../../services/api';
import { 
  ShieldCheck, LogOut, Clock, Sparkles, AlertCircle, 
  BookOpen, Download
} from 'lucide-react';

const StudentDashboard = () => {
  const navigate = useNavigate();
  const [seatData, setSeatData] = useState(null);
  const [loading, setLoading] = useState(true);
  const rollNo = localStorage.getItem('userRollNo');

  useEffect(() => {
    const fetchSeat = async () => {
      if (!rollNo) {
        navigate('/login');
        return;
      }
      try {
        // Fetches the specific allocation generated by the CSP Algorithm [cite: 21]
        const response = await apiService.getStudentSeat(rollNo);
        setSeatData(response.data); 
      } catch (error) {
        setSeatData(null);
      } finally {
        setLoading(false);
      }
    };
    fetchSeat();
  }, [rollNo, navigate]);

  const handleLogout = () => {
    localStorage.clear();
    navigate('/login');
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-slate-50 flex flex-col items-center justify-center space-y-4">
        <div className="w-10 h-10 border-4 border-indigo-600 border-t-transparent rounded-full animate-spin"></div>
        <p className="text-indigo-600 font-bold tracking-widest text-[10px] uppercase">Syncing Nagpur Grid...</p>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-[#F8FAFC] text-slate-900 font-sans p-6 md:p-12 animate-in fade-in duration-700">
      <div className="max-w-5xl mx-auto">
        
        {/* Header Section: Nagpur Division Portal [cite: 35] */}
        <header className="flex justify-between items-center mb-10">
          <div className="flex items-center gap-3">
            <div className="bg-indigo-600 p-2.5 rounded-2xl shadow-lg shadow-indigo-100">
              <ShieldCheck size={28} className="text-white" />
            </div>
            <div>
              <h1 className="text-xl font-black tracking-tight text-slate-900">Eco-Seat <span className="text-indigo-600">AI</span></h1>
              <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest">Nagpur Division Portal</p>
            </div>
          </div>
          <button 
            onClick={handleLogout}
            className="flex items-center gap-2 text-slate-400 hover:text-rose-500 transition-all font-black text-[10px] uppercase tracking-widest bg-white px-4 py-2.5 rounded-xl border border-slate-200 shadow-sm"
          >
            <LogOut size={14} /> Terminate Session
          </button>
        </header>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          
          {/* Main Seat Slip: Digital Manifest [cite: 10] */}
          <div className="lg:col-span-2">
            <div className="bg-white border border-slate-200 rounded-[2.5rem] overflow-hidden shadow-xl shadow-slate-200/50">
              
              <div className="bg-indigo-600 p-8 text-center relative overflow-hidden">
                <h2 className="text-xl font-black text-white uppercase tracking-wider relative z-10">Digital Entry Pass</h2>
                <p className="text-indigo-100 text-[10px] font-bold uppercase tracking-[0.2em] mt-1 relative z-10">Identity Verified • Spring 2026</p>
              </div>

              {seatData ? (
                <div className="p-8 md:p-12 flex flex-col md:flex-row items-center gap-12">
                  
                  {/* UNIQUE SCANNER (QR): QR-Integrated Access [cite: 33] */}
                  <div className="flex flex-col items-center">
                    <div className="bg-white p-5 rounded-[2rem] border-2 border-slate-100 shadow-inner">
                      <img 
                        src={seatData.qr_code} 
                        alt="Unique Scanner" 
                        className="w-44 h-44 object-contain mix-blend-multiply"
                      />
                    </div>
                    <div className="mt-4 px-4 py-1.5 bg-slate-100 rounded-full">
                      <p className="text-[9px] font-black text-slate-500 uppercase tracking-widest flex items-center gap-2">
                         <ShieldCheck size={10} className="text-indigo-600" /> Secure Token Verified
                      </p>
                    </div>
                  </div>

                  <div className="flex-1 w-full space-y-6">
                    <div className="space-y-1 pb-4 border-b border-slate-100">
                      <span className="text-[10px] font-black text-slate-400 uppercase tracking-widest">Candidate Information</span>
                      <h3 className="text-2xl font-bold text-slate-900 tracking-tight">{seatData.name}</h3>
                      <p className="text-sm font-bold text-indigo-600 tracking-widest uppercase">{rollNo}</p>
                    </div>

                    <div className="grid grid-cols-2 gap-6">
                      <div className="bg-slate-50 p-4 rounded-2xl border border-slate-100">
                        <span className="text-[10px] font-black text-slate-400 uppercase tracking-widest block mb-1">Hall / Room</span>
                        <span className="text-xl font-black text-slate-900 italic tracking-tight">{seatData.room_no}</span>
                      </div>
                      <div className="bg-slate-50 p-4 rounded-2xl border border-slate-100">
                        <span className="text-[10px] font-black text-slate-400 uppercase tracking-widest block mb-1">Assigned Seat</span>
                        <span className="text-xl font-black text-slate-900 italic tracking-tight">{seatData.seat_no}</span>
                      </div>
                    </div>

                    <div className="flex items-center gap-3 pt-2 text-slate-600 bg-indigo-50/50 p-3 rounded-xl border border-indigo-100/50">
                      <BookOpen size={16} className="text-indigo-600" />
                      <span className="text-[10px] font-black uppercase tracking-widest text-indigo-900">{seatData.subject}</span>
                    </div>
                  </div>
                </div>
              ) : (
                <div className="p-16 text-center">
                  <div className="bg-amber-50 w-16 h-16 rounded-full flex items-center justify-center mx-auto mb-6">
                    <AlertCircle size={32} className="text-amber-500" />
                  </div>
                  <h3 className="text-lg font-bold text-slate-900 uppercase">Seating Not Allocated</h3>
                  <p className="text-slate-500 text-xs mt-2 max-w-xs mx-auto font-medium leading-relaxed">
                    The Smart City Optimization Engine has not yet published the conflict-free grid[cite: 13, 21].
                  </p>
                </div>
              )}
            </div>
            
            <button 
              onClick={() => window.print()}
              className="w-full mt-6 bg-slate-900 text-white py-5 rounded-[2rem] font-black text-xs uppercase tracking-[0.3em] flex items-center justify-center gap-3 hover:bg-slate-800 transition-all shadow-xl shadow-slate-200/50 active:scale-[0.98]"
            >
              <Download size={18} /> Download Digital Pass
            </button>
          </div>

          <div className="space-y-6">
            <div className="bg-white border border-slate-200 rounded-[2rem] p-8 shadow-sm">
              <div className="flex items-center gap-3 mb-6">
                <Clock className="text-indigo-600" size={18} />
                <span className="text-[10px] font-black uppercase tracking-widest text-slate-400">Exam Schedule</span>
              </div>
              <div className="space-y-4">
                <div className="flex justify-between items-center pb-3 border-b border-slate-50">
                  <span className="text-xs font-bold text-slate-500">Date</span>
                  <span className="text-xs font-black text-slate-900 uppercase">31-03-2026</span>
                </div>
                <div className="flex justify-between items-center">
                  <span className="text-xs font-bold text-slate-500">Reporting</span>
                  <span className="text-xs font-black text-indigo-600 uppercase">09:45 AM</span>
                </div>
              </div>
            </div>

            <div className="bg-slate-900 rounded-[2rem] p-8 relative overflow-hidden shadow-xl shadow-slate-400/20">
               <Sparkles className="absolute top-[-10px] right-[-10px] text-white/5" size={100} />
               <p className="text-[10px] font-black text-indigo-400 uppercase tracking-widest mb-3">Nagpur Safety Protocol</p>
               <p className="text-xs text-slate-300 leading-relaxed font-medium">
                 Your <span className="text-white font-bold underline decoration-indigo-500">Unique Scanner</span> must be scanned at the hall gate[cite: 33, 38].
               </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default StudentDashboard;